# Generated by Django 4.2.6 on 2023-10-21 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models.store_model
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('main_photo', models.ImageField(default='store/main/main.png', upload_to=products.models.store_model.store_main_photo_path)),
                ('cover_photo', models.ImageField(default='store/cover/cover.png', upload_to=products.models.store_model.store_cover_photo_path)),
                ('product', models.ManyToManyField(to='products.product')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
