# Generated by Django 4.2.6 on 2024-04-06 11:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductScraper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scraper', models.CharField(max_length=100)),
                ('start_urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('extractor_type', models.CharField(choices=[('xpath', 'Xpath'), ('regex', 'Regex'), ('json', 'Json'), ('data', 'Data')], max_length=5)),
                ('pattern', models.CharField(max_length=200)),
                ('field_name', models.CharField(max_length=50)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productscraper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productscraper',
            name='available',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_available', to='products.rules'),
        ),
        migrations.AddField(
            model_name='productscraper',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_by', to='products.rules'),
        ),
        migrations.AddField(
            model_name='productscraper',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_condition', to='products.rules'),
        ),
        migrations.AddField(
            model_name='productscraper',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_description', to='products.rules'),
        ),
        migrations.AddField(
            model_name='productscraper',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_discount', to='products.rules'),
        ),
        migrations.AddField(
            model_name='productscraper',
            name='html',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_html', to='products.rules'),
        ),
        migrations.AddField(
            model_name='productscraper',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_images', to='products.rules'),
        ),
        migrations.AddField(
            model_name='productscraper',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_meta', to='products.rules'),
        ),
        migrations.AddField(
            model_name='productscraper',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_name', to='products.rules'),
        ),
        migrations.AddField(
            model_name='productscraper',
            name='original_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_original_price', to='products.rules'),
        ),
        migrations.AddField(
            model_name='productscraper',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_price', to='products.rules'),
        ),
        migrations.AddField(
            model_name='productscraper',
            name='ratings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_ratings', to='products.rules'),
        ),
        migrations.AddField(
            model_name='productscraper',
            name='shipping_charges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper_shipping_charges', to='products.rules'),
        ),
    ]
